[package]
name = "concat_bytes"
version = "0.1.0"
authors = ["KokaKiwi <kokakiwi@kokakiwi.net>"]
license = "MIT"
description = "A concat_bytes! macro which concat byte arrays"

[lib]
name = "concat_bytes"
plugin = true
